### ISSUE TITLE
Error: rpool/data/... is not a valid filesystem

### ISSUE THREAD

**Issue by slideup-benni** [husisusi/officeonlin-install.sh#122]
I get the same error as described in https://github.com/husisusi/officeonlin-install.sh/issues/120

`Error: rpool/data/subvol-1109-disk-1 is not a valid filesystem`

I'm using a Debian 8 LXC-Container inside Proxmox with zfs.

my `df -h`:

```
Filesystem                     Size  Used Avail Use% Mounted on                              
rpool/data/subvol-1109-disk-1   20G  635M   20G   4% /
none                           492K     0  492K   0% /dev
tmpfs                          1.6G   44K  1.6G   1% /run
tmpfs                          5.0M     0  5.0M   0% /run/lock
tmpfs                          3.2G     0  3.2G   0% /run/shm
```

Can I work around it?

**Comment by aalaesar** [comment]
Hi there!
I'll change the file system test because it's causing to much restriction for now.
you can delete lines [25 to 27](https://github.com/husisusi/officeonlin-install.sh/blob/master/lib/checksys.sh#L25) in file [lib/checksys.sh](https://github.com/husisusi/officeonlin-install.sh/blob/master/lib/checksys.sh).
the script will continue on your FS.
regards, 
Aal.

**Comment by slideup-benni** [comment]
Very thank you. It is working now.

**Comment by aalaesar** [comment]
Hi. can you test it with the latest version ?
Could you close the issue if it work ?
Thanks 😄

**Comment by slideup-benni** [comment]
Now i get: 

![unbenannt3](https://user-images.githubusercontent.com/12446028/30106950-7c12c00a-92fd-11e7-8f63-b55d547e5485.PNG)

(`git rev-parse HEAD` : 1f2529a21d409cfec1e52b2d45ff826239d87ca4)
