### ISSUE TITLE
Add Package Support

### ISSUE THREAD

**Issue by embed-3d** [husisusi/officeonlin-install.sh#131]
Collabora offers now for Linux x86_64 debian packages for Debian 9, Debian 8 Ubuntu 16.04, CentOS 7 and openSUSE 42.2.

https://www.collaboraoffice.com/code/

Maybe we can add a option that installs those packages and generates the certificates and helps with all the other little details that are not done by the packages?

**Comment by aalaesar** [comment]
Hi there!
Could you elaborate ?
Are you looking for using the official collaboration packages instead for building it from source and having a post installation script  ?
Or maybe you're suggesting we should use collabora's packaging scripts ?
If it's the first answer, then it's a little bit off from the purpose of this script initial  purpose (that is to provide a easy way to compile libreofficeonline from source) even if the collabora branch is used by default.
But it still would be a nice addition 😉
Regards

**Comment by embed-3d** [comment]
Right now the whole compile process needs hours and is depending on your local setup. 
So my suggestion is to implement the install procedure with packages from the collabora repo as additional option in the script, like: `./officeonlin-install.sh --use_packages`. This avoids the long compilation process. 
An other problem of the packages is, that there is some "configuration" necessary after the installation, to get it running. (These after install steps are right now not properly documented)
Regards

**Comment by aalaesar** [comment]
Ok @embed-3d 
I may look into that for future version.
For now i'm working on figuring out the packaging part  of libre office 😕 
a post-installation script will come handy once this part is figured out... hopefully 😄

**Comment by aalaesar** [comment]
Some updates:
I managed to get some deb packages out of libreoffice compilation but their were too small (only some to Ko) to be something working properly.

As I have very few time to work on it by now,
Any help would be welcome here.
Regards

**Comment by embed-3d** [comment]
@aalaesar I think I can support you with this, since I have some packaging experience. Can you show me what you have done up to now? (I might need some time  until I can support you since I'm currently change my ci system)

**Comment by aalaesar** [comment]
Thanks @embed-3d .
I've accidentally destroyed my testing instance and lost the build options since my tests.
For most of the story:
I figured out that **Libreoffice** had its own package generator that have to be triggered at compilation
while the **online** project come with a _debian_ folder (at least for the collabora branches)  used as configuration for the `debuild` tool.
For Libre office , most of the options are here: https://wiki.documentfoundation.org/Development/BuildingOnLinux#Build_DEB_and.2For_RPM_Packages with tweaking on the distro name.
but I also found out that the specified distro get the '-devel' suffix if another option is not used (I have to research it again)

I worked on the "distro" integration into the script to prepare the packaging.

Then I successfully get a full libre-office compilation with deb packages generated but I did not get the time to go further (testing packages elsewhere) and like I said before, the packages looks wrong judging by their sizes.

For the **online** packaging, this may be more tricky. It is a post build process that should be mostly "classic" for an experimented packager (that's I'm not at all 🙂 atm ) but as the project may come with **lots of various** configuration content (and configured dependencies) - if not at all depending of the branch- inside the `debian` folder,
I'm still wondering how to automate this:
- Having it's own config for the debian packaging ?
- /Creating/Patching  the config for the packaging inside the project ?
- As package dependencies are generated in this conf, how could this affect the set feature of the script? by selecting the correct distribution for libreoffice ?
- ... Probably other questions to ask later....

What do you think about it ?

working devel branch here : https://github.com/aalaesar/officeonline-install/tree/Devel
if you want to check
Regards, Aal.

**Comment by embed-3d** [comment]
@aalaesar  Here are my thoughts on the topic:

 I think we don't need to build **Libreoffice** like mentioned in the link. I'm pretty sure they build with these scripts the debian/rpm packages for the distributions. 
If you go through our script we only use the installdir of libreoffice like here `-with-lo-path=${lo_dir}/instdir`. If we use the existing debian packages instead of compiling [libreoffice](https://packages.debian.org/stretch/libreoffice) the equivalent path of `${lo_dir}/instdir` should be here `/usr/lib/libreoffice/`. If this works, we can drop the libreoffice compilation and use the existing packages. That would make everything faster!!!!! And it would be very easy to build the other packages!!!

I think we will end up in building our own loolwsd package and maybe some libpoco packages.

We could automate it like this:
- maintain our own debian folder and replace/insert/patch it into the cloned repo.
- It will also improve the maintainability since you don't need to use hours/days to compile

Suggestion about the next steps:
1. Find out how to use libreoffice packages to build loolwsd
2. Find out how to other packages to build loolwsd like [libpoco](https://packages.debian.org/search?suite=stretch&searchon=names&keywords=libpoco) 
3. prepare/improve build script for packaging
4. generate debian folder for loolwsd
5. ....

Regards,
Philipp

**Comment by aalaesar** [comment]
Hi embed-3d 
This is a nice idea. 👍
 Someone may test it.
 However if I understand correctly, online and core version of Libre-office are tightly integrated. 
This is why I had to create the 'set' feature. Because loolwsd did not work correctly when only using master branches. 

The main drawback is the distribution  limitations : most distribution are using older versions of libre office because they are stable. This would hold the used version of online too if integrated properly. 
This is not a issue at all, just a drawback.
 So the choice should be up to the user.🤔

However I would not rely on a external repository, just to keep packaging configuration. 
Because its management would be time consuming. ☹️
But I'm ok to store the packaging conf inside this repo to be downloaded allong it.☺️

''• It will also improve the maintainability since you don't need to use hours/days to compile'' 
Sorry I don't get it, those points are not usually related.  But this would ease some testing for sure...🤔

I understand your enthusiasm, however  the goal of this script is not to distribute a new distribution but to allow its users to make their own by automating most of the integration and still leaving them a lot of control over the result.

Regards Aal

**Comment by husisusi** [comment]
@aalaesar 
maybe we should try to use Flatpak?
