### ISSUE TITLE
Error while running Script.

### ISSUE THREAD

**Issue by karthikjoe** [husisusi/officeonlin-install.sh#134]
Hi @husisusi @aalaesar @morph027 @sergey-dryabzhinsky @Gomez @embed-3d 

I have run this script but getting this error.
I have pasted all  .sh files in lib director and bin direcrtory.

./officeonline-install.sh: line 22: /home/joejack3388/lib/*.sh: No such file or directory
./officeonline-install.sh: line 81: /home/joejack3388/lib/default.cfg: No such file or directory
./officeonline-install.sh: line 110: sh_interactive: parameter null or not set

**Comment by aalaesar** [comment]
Hi there 😄 
That's odd 😕, this imply that the local path is not properly detected.
It's defined line 16 : `ScriptFullPath="$(dirname "$(realpath $0)")"`

Could you try to run the script with `bash -x` so you can have a better view of bash's underline work ?

Also, could you tell us more about how you installed the script on your host ?
Regards.
Aal

**Comment by karthikjoe** [comment]
Hi @aalaesar

Thanks for your reply...
I own vps in Google cloud.
It fresh Ubuntu 16.04lts..
I paste this file on my home directory and also pasted all lib & bin in that particular directory finally run using this cmd.
Sudo ./officeonline-install.sh.

**Comment by husisusi** [comment]
Hi karthikjoe,
like @aalaesar said, try this:
sudo -s
bash -x /Path/to/officeonline-install.sh

**Comment by karthikjoe** [comment]
Hi @husisusi @aalaesar 

Now i try with your way but still i am getting error.

joejack3388@test:~$ sudo -s bash -x officeonline-install.sh
++ id -u
+ [[ 0 -ne 0 ]]
+++ realpath officeonline-install.sh
++ dirname /home/joejack3388/officeonline-install.sh
+ ScriptFullPath=/home/joejack3388
+ for mylibrary in '$ScriptFullPath/lib/*.sh'
+ source '/home/joejack3388/lib/*.sh'
officeonline-install.sh: line 22: /home/joejack3388/lib/*.sh: No such file or directory
+++ tr : ' '
+++ echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /usr/local/sbin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /usr/local/bin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /usr/sbin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /usr/bin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /sbin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /bin/curl
++ for subpath in '$(echo $PATH|tr '\'':'\'' '\'' '\'')'
++ ls /snap/bin/curl
+ '[' -z /usr/bin/curl ']'
+ [[ 0 -gt 0 ]]
+ source /home/joejack3388/lib/default.cfg
officeonline-install.sh: line 81: /home/joejack3388/lib/default.cfg: No such file or directory
+ '[' -n '' ']'
+ '[' /home/joejack3388 '!=' /home/joejack3388 ']'
+ '[' -s /home/joejack3388/officeonline-install.cfg ']'
+ '[' -s /etc/loolwsd/officeonline-install.cfg ']'
+ '[' -s /home/joejack3388/officeonline-install.cfg ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' -n '' ']'
officeonline-install.sh: line 110: sh_interactive: parameter null or not set

**Comment by aalaesar** [comment]
Hi.
So the local path is correctly detected however bash somehow miss most of the file.
I recommend you to download the script  with git to be guaranteed to have all the required files ☺️

**Comment by karthikjoe** [comment]
Hi @aalaesar 
I download fresh copy from git and trying to run officeonline-install.sh
it's running successfully..But i am waiting for Error in Mid stage or End stage.
I hope this one ends without any error..
Thank Q all who make this and who help me install..Once again thank Q all..

**Comment by embed-3d** [comment]
@karthikjoe it looks like that you want to execute the folder of the git repo. The actual script is located in a folder called officeonline-install.sh. so the actual script ist located in ~/officeonline-install.sh/officeonline-install.sh

**Comment by karthikjoe** [comment]
@embed-3d 
I have downloaded zip file from github then i extract into my home folder after i am inside of that extrated folder then only i ran this bash cmd..
Is this Correct Way...Am i did Correct..?

**Comment by embed-3d** [comment]
@karthikjoe you could try to use the git clone command, go into the cloned directory and execute the script. When I know it right there is some difference when you download a zip or clone it (right's, ...)

**Comment by karthikjoe** [comment]
@embed-3d 
Already it's running at 5 hours and i don't know when it is finished...... I have another some doubts is that any post installation step are available..?
And One more thing is is this office is limitless..? Bcz I saw it on NC.In NC forum says it's limitless.

**Comment by ibeardslee** [comment]
Not limitless. From memory, the defaults are 200 connections & 100 documents at a time. But that can be changed at build time, consider the size of your server before you make changes.

Once the build is done, you'll need to do some tweaking of configurations to allow your 'document server' (I assume you are using NextCloud) to access the new Libreoffice Online server. I'd be suggesting that you do ensure that it is behind something like apache or nginx to make sure that it is being served with https. There is plenty of documentation around about how to do that.

Depending on the CPU & memory of the server doing the build it can take a while, my own builds take just over 4.5 hours.  We are looking at how that can be improved by having a machine for building it that has plenty of memory, CPU and an SSD to get it done quickly and turning that into our own docker image that ends up being pushed to load balanced servers.

**Comment by karthikjoe** [comment]
Hi @ibeardslee 
Thanks For you Information and one more help required from you. i am familiar with Linux & Unix so can you give link for post installation steps..?

And another one thing while that onlineoffice-install running my vps server SSH connection dropped due to network connectivity then after i don't know wat to do..!!
Then i started with beginning this time that installer throws some errors.Then I'll reset my vps today and again now started from first step.
Sry for my bad English..and also i am new to Linux and web servers. but still trying learn from Linux & UNIX.

**Comment by karthikjoe** [comment]
OMG Again my SSH failed due to n/w connectivity and installation was stopped...Is that any way continue installation or must start from beginning...?

Updated : Again once disconeected on 12.40pm IST

**Comment by aalaesar** [comment]
Hi  there @karthikjoe.
Your server either temporary freeze because of the compilation load **or**  there is network interruption between your ssh client and your vps **or**  the ssh server is configured to drop _inactive_  (user is not taping anything ) ssh links.
Because the script is run as a child process of your terminal (more like grandchild), the system kill it when the link is lost (because it kills all children of the terminal process).

First you could 'detach' the script from your terminal session   using ` &` at the end of your command to make it run in background.
But you may loose terminal  output if the link goes down again.
I recommend  using the `screen` command because it can recover lost terminal output. 
You may find more about it on the Internet.

As I suppose the connection fails while compiling libreoffice, you may run the script again with  options `-f lo -f lool -f poco` to force full recompilation.

That's  being said, welcome to the linux community of system administrators and developers. This is not a easy path. It is requires a lot of autonomy and adaptation to be able to progress. You won't always find the perfect answer/tutorial for your needs
I recommend you to seek for tutorials about linux administration for beginners in your native language.

Also **I don't recommend**  you to use this script on a public cloud server if you intend to use it for personal 'production' service.
It install sooooo many things required for compilation that it **dramatically** increase the server's surface of attack by hackers.

Lastly here's the post-install tutorial you're looking for : 
https://nextcloud.com/collaboraonline
As I said before, this does not cover perfectly our case. You'll have to adapt it, skip parts, change configuration, etc.

"Bon courage" :relaxed:
 and hang on ! :muscle:
Aal.

**Comment by karthikjoe** [comment]
Thanks @aalaesar 
Already my VPS working with collabora CODE And only office community server.
Yes i am going to drop this idea.And one more thing i am trying to search manual install and compilation guide for libreoffice online. But my bad luck i don't find any link. Can you have any link or guide for this.?
And finally how to remove limitaitons from libreoffice online..?
Thanks for your support.

**Comment by ibeardslee** [comment]
To change the connection and document limits for LibreOffice Online, the configuration file _officeonline-install.cfg_ needs to be changed, remove the comments _#_ and change the limits.
```
#lool_maxcon=200
#lool_maxdoc=100
```
I **would not** getting too carried away until you know how it is being used, you are more likely to find that the limit is the server resources not the number of clients with documents open at the same time.

I haven't seen any other manual install & compilation guide for Libreoffice Online, the work has already been done quite nicely with this script. If I wanted to do something different I would start with this script and take it apart to find out how it works.

**Comment by karthikjoe** [comment]
Hi @ibeardslee and All...Thanks for patience and responses..
Basically i am a windows guy..So only i don't know anything on windows.It's OK but i can learn.
i found one you tube video for manual installation and compilation of LibreOffice online.
But in that Git Package i don't know where is limitation was mentioned. Anyone of you guys guide me to identify and make changes on that limitations.
And one more thing is now i am using Collabora CODE online docker in my next cloud server.
And i want remove limitation on that docker image. I believe you guys you're help me..

**Comment by aalaesar** [comment]
Hi @karthikjoe ,
the connexions limitations are hard-coded inside the websocket server during compilation.
SO as the docker only contain compiled software, you can't do much about it.
Limitations values are passed as options to the compiler during the build of the WebSocket
That's why this script exists in the first place. 😉 
You're free to read it to get more clues about it, as suggested by @ibeardslee.
Regards.
Aal

**Comment by karthikjoe** [comment]
Ok Thanks @aalaesar 
@ibeardslee  can you help me to learn this..? and thanks in advance.
And also i req to all anyone pls make Beginner guide for installing & compiling LibreOffice online for Linux beginners like me..There are huge amount of people around on this world without knowing this...If it's possible that all credits goes to That King Maker(Guide Owner)....

**Comment by aalaesar** [comment]
Hi @karthikjoe.
Building the libre office online project is definitively **not** an easy task.
It requires a lot of existing knowledge to begin with.
That's one of the main reason guides are rares, the second reason being that most people don't have available time and/or motivation to document freely this complex processus with **a lot** of variables.
(but I confess that I did'nt have time to check if more guides existed since quite a while...)

Also, As you asking for "disabling" the limitations, I feel I must be a little more specific about this point:
libre-office online **`requires`** those limitations by design. (This is the web-socket design)
Consider this as a performance/security feature.

So you if you want more files/connections opened simultaneously for you service, you may either change the `lool_maxcon` and `lool_maxdoc` parameters in this script before running it
or/and
Want to scale your container/loolwsd horizontally. (more  servers running in parallel behind a load balancer)
I kindly invite you to read the readme.md file that try to explain accurately how this script work and can be used.

Regards.
Aal.

**Comment by karthikjoe** [comment]
Thanks team...
Pls close this issue..but onething this script not fully supported by using SSH.

**Comment by aalaesar** [comment]
Hi @karthijoe
Yet, no people have reported issue with ssh.
If your terminal close the connection on regular basis you may need to
- Change the terminal configuration to keep the connection  alive
- run the script in back ground or detached from the terminal link using the tool **screen**  for example.

Regards.
Aal.

**Comment by karthikjoe** [comment]
Hi @aalaesar sry for delay reply.
After 5 days to learn screen I have successfully ran script using screen cmds. but now i don't know wat to do after completion of script.

Update:
I don't see any msg box after completion of script.What can i do?
loowsd service not running after try to manual start but still loolwsd service won't start..

**Comment by aalaesar** [comment]
Hi @karthikjoe,
sorry I have zero time available at the moment.
I recommend you to look over the nextcloud's collabora guide that have been linked earlier.
Regards.
Aal.

**Comment by aalaesar** [comment]
Hi.
Cans this issue be closed ?
