### ISSUE TITLE
Configuration file not working as expected

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#137]
### Description: 
Described Poco variables in custom config file are not properly overriding default poco variables
### Environment:
**Os:** Ubuntu 16.04
**script command:** `sudo officeonline-install/officeonline-install.sh -f poco -f lool`
**config file used :** $HOME/officeonline-install.cfg 
**content:**
```shell
sh_interactive=false
poco_version_latest='1.7.9p2'
```
### Expected result:
poco_version_latest=1.7.9p2
poco_version=1.7.9p2
poco_version_folder=1.7.9
poco_dir="/opt/poco-1.7.9p2-all"
### Current result: 
poco_version_latest=1.7.9p2
poco_version=1.8.0.1
poco_dir=/opt/poco-1.8.0.1-all
poco_version_folder=1.8.0.1
### Workaround:
Define all poco variables with their default value in the custom configfile except poco_version_latest
this is counter-intuitive

**Comment by tavinus** [comment]
Hi, this is also broken for libreoffice (and possibly lool).

I am trying to change LO's version since the current version does not compile on my Ubuntu but it always changes back to `distro/collabora/cp-5.3`.

I have added several prints of `${lo_src_branch}` and noticed it reverts when you call:
```
source "$ScriptFullPath/bin/systemSetup.sh"
```
It seems to me that the function FindOnlineSet() then cannot find a proper repo and resets it here
( `systemSetup.sh` ):
```
if [ -n "${set_name:?}" ]; then
  echo "Searching for a set named $set_name..."
  my_set=$(FindOnlineSet "$set_name" "$lo_src_repo" "$set_core_regex" "$lool_src_repo" "$set_online_regex" "$set_version")

  ### THIS EXECUTES AND RESETS IT, so "$my_set" is not being parsed ok
  if [ -n "$my_set" ]; then
    lo_src_branch=$(echo $my_set | awk '{print $1}') && echo "Core branch: $lo_src_branch"
    lool_src_branch=$(echo $my_set | awk '{print $2}') && echo "Online branch: $lool_src_branch"
  fi
fi

### Setting manually HERE works for me, as in:
lo_src_branch='distro/collabora/cp-5.1'
```
**EDIT: manual setting added above** 

So the problem seems to be in the `FindOnlineSet()` function but I could not debug that yet.

**Comment by aalaesar** [comment]
Hi @tavinus 
Can you try with `bash -vx` in the script call ? So we might see what's the value for my_set ?
Regards, Aal.

**Comment by aalaesar** [comment]
Never mind, (took me some minutes to go back on the code)
What's happening here is:
the process **always** override _lo_src_branch_ & _lool_src_branch_ when it searchs **and** find a set.
So you can prevent it to enter the if block by setting `set_name=""` in your configuration file, as a workaround but you will have to specify also both lo/lool_src_branch or it will use the default (master)

**Comment by tavinus** [comment]
Hi! I ended up reverting my VM to a previous snapshot to try other stuff and I can't really try at this point.

If I remember correctly, it would work if I used the regex var instead of the other ones.
It is indeed a bit confusing on the current state, specially because of the overrides.

The main problem is obviously to have a compile error after a few hours compiling (which is kind of normal for this, but still a pain).

I wonder if there is anywhere to find the set names/versions?
