### ISSUE TITLE
git clone  ${*_src_repo} --depth 1 ${*_dir}

### ISSUE THREAD

**Issue by ibeardslee** [husisusi/officeonlin-install.sh#157]
Is it sane to use --depth 1 in the git clones to reduce the time/space to grab some git repos? Although in the greater scheme of things this is a smaller part of the time taken and the final space requirements it could be a time saver for people continually building and testing.

Only thing I haven't worked out is if some of the options to use different commits (eg --libreoffice_commit)=COMMIT and --libreoffice_online_commit)=COMMIT) would fail if that was chosen. But if some further smarts are built into it the option could be take to use --depth 1 or not.

./bin/corePrep.sh  line 17
```
-- git clone ${lo_src_repo} ${lo_dir}
++ git clone ${lo_src_repo} --depth 1 ${lo_dir}
```

./bin/onlinePrep.sh  line 16
```
-- git clone ${lool_src_repo} ${lool_dir}
++ git clone ${lool_src_repo} --depth 1 ${lool_dir}
```

**Comment by aalaesar** [comment]
Hi @ibeardslee, thank you for your suggestion ☺️ 
I'm not a super git expert. As I recall, shallow clones have limited functionnality like limited acces to the branches and global commit history.
I remember testing it in the beginning to switch dynamically between commits and having troubles to get the [SearchGitCommit](https://github.com/husisusi/officeonlin-install.sh/blob/master/lib/SearchInGit.sh#L2) function working properly.
_the goal being: be able to target a branch and commit automatically with the fewer parameters possible for the user. (this have changed since the addition of the "set" concept)_
When rebuilding from the same host, the script re-use and eventually update the repository to trigger a new build so the first big clone of libreoffice whould only inpact execution time once.
Also the time taken by the first clone depends on the Internet speed connexion and CPU, so it may vary, but this may only take a few minutes (compared to the hours long it takes to build LibreOffice)

So what I'm trying to say is:
Switching to shallow clone may be a good optimisation but this will need refactoring the SearchGitCommit function to get commit infos directly from github
AND IF it is possible to shallow clone directly from a commit.

On my part I'm not sure it worth the time to do that. 😕

Of course, you're welcome to contribute, if you find a way to make commit targeted shallow clones and you want to share it 

Regards, 

Aal

**Comment by ibeardslee** [comment]
I thought that might be the case. Just wanted to check the thoughts of those that know the code better than myself. I think I'll stick with my own hack of the scripts after cloning this repo for now ..
```
sed -i  s/_src_repo}/"_src_repo} --depth 1"/  /opt/officeonline-install/bin/onlinePrep.sh
sed -i  s/_src_repo}/"_src_repo} --depth 1"/  /opt/officeonline-install/bin/corePrep.sh
```

**Comment by aalaesar** [comment]
I hope I didn't sounded harsh. 😅. I was just trying to explain myself.
I think it might  be possible to manage shallow clones on a per commit way. If it is possible to remotely find tags and commit id and make a shallow clone by cloning directly from a commit id, this should work with a medium  rewrite of the searchGitCommit function. And some adjustments in the sub-scripts.
I haven't any free time available for now to check on  this  :disappointed:
Regards 
Aal.

**Comment by aalaesar** [comment]
I home I didn't sounded harsh. 😅. I was just trying to explain myself.
I think it might  be possible to manage shallow clones on a per commit way. If it is possible to remotely find tags and commit id and make a shallow clone by cloning directly from a commit id, this should work with a medium  rewrite of the searchGitCommit function. And some adjustments in the sub-scripts.
I haven't any free time available for now to check on  this  :disappointed:
Regards 
Aal.

**Comment by ibeardslee** [comment]
All good, didn't come across as harsh.
'Free time' quickly fills up with other things. That dirty wee hack of mine will do the job until I have the time/motivation to investigate further. But I'm pretty sure we agree that the gains made in terms of time/space/bandwidth are relatively insignificant for the amount of effort to do it 'properly'.
Cheers,
Ian

**Comment by Ark74** [comment]
Not a git expert but I have tested using --depth 1 on several scripts, and if the repo is huge, it can substantially reduce the weight on the package just downloading the latest and not the complete historical commits.

:+1:
