### ISSUE TITLE
Cannot edit in nextcloud ?

### ISSUE THREAD

**Issue by guidtz** [husisusi/officeonlin-install.sh#160]
Hello,

   I compile libreoffice-6-1 with you're script. All the compilation is done without errors.

loolwds is ready on server. 
I can connect Nextcloud with it via an apache proxy.

When I select a document in nextcloud, libreoffice is open, but ...
I cannot add caracters in document or in calc
Very strange. 
Do you have an idea ?

Regards

**Comment by Ark74** [comment]
As you see the script will compile the latest release of several components which are commonly broken since they are not always build to be released together.

You'll need to seek for a working combination and set those values on the officeonline-install.cfg file in order to get a known working kit, which the way the different components evolve (pretty quickly) is beyond the reach of this script (unless someone codes that automation).

Take a look at https://github.com/husisusi/officeonlin-install.sh/issues/155 for some pointers.
