### ISSUE TITLE
openjdk error

### ISSUE THREAD

**Issue by titansmc** [husisusi/officeonlin-install.sh#207]
I get this, do I have to worry?
```
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
/root/officeonlin-install.sh-ops-office03/bin/systemSetup.sh: line 78: openjdk-8-jdk: command not found
```

**Comment by quenenni** [comment]
From the code, it shouldn't try to execute the command openjdk, but add the package openjdk to the list of packages to install.

Maybe because there is a blank lilne just before.
https://github.com/husisusi/officeonlin-install.sh/blob/67089a338bddf554806065edc216d0e7cd14dc89/bin/systemSetup.sh#L78

I'm not using the same version of the script, so I can't confirm.

Can you try to edit the file, remove the blank line (line 77) and give it a new try?
