### ISSUE TITLE
How to unset docs/connections

### ISSUE THREAD

**Issue by Ark74** [husisusi/officeonlin-install.sh#27]
I see there is a value for 
lool_maxcon=200
lool_maxdoc=100

Would compile with -1 disable this, or maybe a 0, i guess -1 would have more sense.
Or just to put a number like, 999999 to make it (virtually) unlimited or restricted to compilation.

I'm building with -1 see what happens.
Do you have any idea?

**Comment by husisusi** [comment]
I don know.
Please let me know if -1 works

**Comment by Ark74** [comment]
Here the results:
Compiling with 0 you can open several files.
Compiling with -1 you can open several files.
Compiling with 9999 you can open several files. :smile: 

On each one the Admin console is no longer working.
It shows 0MB, 0 documents,etc.

Do you have the same behavior?

**Comment by Ark74** [comment]
If you wanna test it yourself.
Please by pm send me your domain so i enable it.
Mention what option you'll like to test.

It will be up for a day or two.
See you.

**Comment by aalaesar** [comment]
Hello Ark74.
Just to be safe, does the admin console works with the default values ?
We need to look deeper in the loolwsd doc/code to properly setup the compilation options.
Regards.

**Comment by aalaesar** [comment]
Just looked in the configure.ac and the wsd code.
seems to be hard coded in the websocket deamon with some rules over the value:
* must be positive
* maxdoc can't be greater than maxcon
* minimums are 3 for maxcon and 2 for max doc (auto applied during configuration)
* defaults are 20 maxcon & 10 maxdoc

I also looked over google with "websocket max connections" and saw a variety of questions and articles about WebSocket limitations.
As it works over TCP, there's a barrier of 64K connection, but i'm not even sure a WS engine could support all those connections. (some reports about 10k)

So, as I understand your frustration about having a limitation, this seems to be intentionnal both because of tech limitation and ressource management. (as  unlimited connections **will lead** to unlimited ressource consumption **and eventually** to ressource shortage issues )

**Comment by Ark74** [comment]
Oh, that! is interesting.
Yeah, i believe the hard limit will be hardware resources, so i see very difficult to reach technical limitations.
Anyway thanks.
I can't confirm if admin is working with default values, sorry.

**Comment by husisusi** [comment]
I confirm, admin is working with default values.

**Comment by husisusi** [comment]
@Ark74, 
You reported false information. :|
1. Admin console working with 0 an -1, but you just need to empty your Browser Cache.
2. With 0 and -1 you can just open 10 Docs
3. I test it with 999 and it working properly. (Tested with 50 Docs)
 
I just lost my time with this...

**Comment by Ark74** [comment]
> I just lost my time with this...

You didn't need to lost any time, i said.

>If you wanna test it yourself.
> Please by pm send me your domain so i enable it.

Cheers.
