### ISSUE TITLE
Separate code build and result apps

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [husisusi/officeonlin-install.sh#57]
It's only suggestion, but may be all of builded apps must be installed to some directory/root in /opt or even in /home/lool?
It would be helpful then someone (like me) creating VM template.
May be even to create some automated update of LooL template.

**Comment by aalaesar** [comment]
Hi @sergey-dryabzhinsky,
A big yes from me on this point.
This point is why I opened #34 and #31 initially.
I have started digging on this one since my first PR here and I have elaborated the beginning of a solution:
### For LibreOffice:
Digging into the collabora's container I found they use they own deb  packages to install libreOffice Core, writter, calc and draw **only**.
(in fact they package everything and use deb and apt to create the container, this allow to have a minimal working loolwsd system, without gcc, etc)
I found this to be a good idea so I created for myself some tasks:
- [_] reduce LO to minimum required for loolwsd
- [_] uses packaging script from core itself to generate libreoffice deb packages
- [_] have another extra script to create the container

### For Poco
Nothing done yet on my side

### For Lool
I saw that the install target of `make` copy most of the loolwsd binaries into /usr/local/
so I noted to myself to update the systemd conf file of loolwsd to point to the installed loolwsd binarie instead of the compiled one.
So I search first what conf file loolwsd was using in order to test various files and binaries location.
I ended-up starting to work on #31 instead for the build really lack an advanced configuration feature.

Since then, well I haven't have many free time to work again on the repo. 😞

**Comment by sergey-dryabzhinsky** [comment]
I understand. It will take time to dig into this.

Most paths can be changed via `./configure --prefix=/opt/ohmylool/usr`.
Or via `make INSTALL_ROOT=/opt/ohmylool`.
Not sure about second. Sometimes bicycle can be found in build scripts.

**Comment by pavinjosdev** [comment]
Is there any possibility to build it on one server and then transfer the complied binaries to another server? Specifically this is taking too long to build on a modest cloud server, so I'd like to do it on a dedicated server and then distribute the binaries to cloud servers.

Sorry if this is just a plain dumb idea.
