### ISSUE TITLE
showstopper: sysntax error

### ISSUE THREAD

**Issue by rochelmeyer** [husisusi/officeonlin-install.sh#92]
Hi, many thanks for this script and sorry for me not having more to contribute than an error that i stumbled upon. 
This is on a hosted v-server, ubuntu 16.04 server. Script starts, downloads many packages, everything looks good and then: 

E: Unable to find a source package for libreoffice
lool:x:119:127::/opt/lool:/bin/false
chown: cannot access ‘/home/lool’: No such file or directory
./officeonline-install.sh: eval: line 448: syntax error near unexpected token `)’

I can create /home/lool and make that error go away, but the syntax error stays. 
Thanks a lot for any hints or fixes.

**Comment by aalaesar** [comment]
Seems that the main cause is this one:
`E: Unable to find a source package for libreoffice`
try to delete /opt/lool, then rerun the script
Do your host have full access to github ?
can you send more logs?

**Comment by Kassiematis** [comment]
Where is /opt/lool coming from? Did you change lool_dir="/opt/online"?

**Comment by Kassiematis** [comment]
I have installed a vanilla Ubuntu and i got the same error.

./officeonline-install.sh: eval: line 448: syntax error near unexpected token `)’

**Comment by Kassiematis** [comment]
The selected tag from git has the `)` character in the title.

![21-7-2017 10-47-55](https://user-images.githubusercontent.com/26070573/28456310-31d70b7e-6e02-11e7-9670-75818e40db93.jpg)

**Comment by Kassiematis** [comment]
Changing line 205 from

` echo "echo Selected Tag: $(echo ${latestTag} | sed 's/.*tag: \(.*\)[)].*/\1/') ${latestTag:0:7}"`

to 

`echo "echo Selected Tag: ${latestTag:0:7}"` wil fix it.

**Comment by Kassiematis** [comment]
@rochelmeyer For some reason your lool user has /opt/lool as homedir. Not ideal for this script.

**Comment by aalaesar** [comment]
@Kassiematis : this remove useful infos and the problem, but do not fix it 😕 
the cause seems to be parenthesis in the commit description messing with the regex.
This show that I should be using escaped double quotes for the echo function to be interpreted by the eval function.
but in this case adding a space in the regex after [)] _should_ fix it without breaking the other ones.
that gives us:
205: `echo "echo \"Selected Tag: $(echo ${latestTag} | sed 's/.*tag: \(.*\)[)] .*/\1/') ${latestTag:0:7}\""`
but I can't test it, I'm away from my test system.

**Comment by Kassiematis** [comment]
Tested and problem with syntax error is solved.
